#FUNÇÕES DE AGREGAÇÃO:
SELECT * FROM products;
SELECT buyPrice FROM products;

#AVG -> DETERMINA A MÉDIA DE UM GRUPO DE VALORES NUMÉRICOS
SELECT AVG (buyPrice) AS 'PREÇO MÉDIO' FROM products;

#COUNT -> CONTA A QUANTIDADE DE VALORES (OU INCIDENCIA DE VALORES) DE UMA TABELA:
SELECT COUNT(*) FROM products;
SELECT COUNT(productCode) AS 'TOTAL DE PRODUTOS' FROM products;

#SUM-> REALIZA SOMA DE UM CAMPO NUMÉRICO ESPECIFICO
SELECT * FROM products;

SELECT SUM(quantityInStock) AS 'TOTAL ESTOQUE' FROM products;
SELECT SUM(quantityInStock * buyPrice) AS 'VALOR TOTAL DO ESTOQUE' FROM products;

#MAX -> DEVOLVE O MAOIR VALOR DE UMA SÉRIE DE VALORES NUMÉRICOS
SELECT MAX(buyPrice) AS 'MAIOR VALOR' FROM products;
SELECT buyPrice FROM products ORDER BY buyPrice DESC;

#MIN -> DEVOLVE O MAOIR VALOR DE UMA SÉRIE DE VALORES NUMÉRICOS
SELECT MIN(buyPrice) AS 'MENOR VALOR' FROM products;
SELECT buyPrice FROM products ORDER BY buyPrice ASC;
